name: Build
on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  gradle:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      #- name: Cache SonarCloud packages
      #  uses: actions/cache@v4
      #  with:
      #    path: ~/.sonar/cache
      #    key: ${{ runner.os }}-sonar
      #    restore-keys: ${{ runner.os }}-sonar

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      #- name: Run Gradle Build
      #  working-directory: ./Src/java
      #  run: ./gradlew check

      - name: Publish package
        working-directory: ./Src/java
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #- name: Publish Test Report
      #  uses: mikepenz/action-junit-report@v4
      #  if: success() || failure() # always run even if the previous step fails
      #  with:
      #   report_paths: '**/build/test-results/test/TEST-*.xml'
      #
      #- name: Upload coverage reports to Codecov
      #  uses: codecov/codecov-action@v4
      #  env:
      #    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
